In [1]:
import pandas as pd
import pandas as pd
from matplotlib import pyplot as plt

# Advertiser

In [2]:
account = pd.read_csv("Data/ad_account.csv")

In [3]:
account.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 110 entries, 0 to 109
Data columns (total 60 columns):
id                                        110 non-null int64
account_status                            110 non-null int64
name                                      110 non-null object
owner                                     110 non-null int64
age                                       110 non-null float64
agency_client_declaration                 110 non-null object
amount_spent                              110 non-null int64
attribution_spec                          110 non-null object
balance                                   110 non-null int64
business                                  110 non-null object
business_city                             3 non-null object
business_country_code                     110 non-null object
business_name                             3 non-null object
business_state                            3 non-null object
business_street                           3 non-null object
business_street2                          0 non-null float64
business_zip                              1 non-null float64
can_create_brand_lift_study               110 non-null int64
capabilities                              0 non-null float64
created_time                              110 non-null object
currency                                  110 non-null object
disable_reason                            110 non-null int64
end_advertiser                            104 non-null float64
is_direct_deals_enabled                   110 non-null int64
is_in_3ds_authorization_enabled_market    110 non-null int64
is_in_middle_of_local_entity_migration    110 non-null int64
is_personal                               110 non-null int64
is_prepay_account                         110 non-null int64
is_tax_id_required                        110 non-null int64
min_daily_budget                          110 non-null float64
partner                                   0 non-null float64
offsite_pixels_tos_accepted               110 non-null int64
spend_cap                                 110 non-null int64
tax_id_status                             110 non-null int64
tax_id_type                               0 non-null float64
timezone_id                               110 non-null int64
timezone_name                             110 non-null object
timezone_offset_hours_utc                 110 non-null int64
user_role                                 110 non-null int64
is_attribution_spec_system_default        110 non-null int64
min_campaign_group_spend_cap              110 non-null int64
end_advertiser_name                       104 non-null object
io_number                                 0 non-null float64
line_numbers                              0 non-null float64
rate_limit_reset_time                     0 non-null float64
has_migrated_permissions                  110 non-null int64
media_agency                              0 non-null float64
tax_id                                    0 non-null float64
is_notifications_enabled                  0 non-null float64
user_tos_accepted                         110 non-null object
funding_source_details                    110 non-null object
rf_spec                                   0 non-null float64
tos_accepted                              110 non-null object
industry_id                               0 non-null float64
industry_name_large                       0 non-null float64
industry_name_medium                      0 non-null float64
industry_name_small                       0 non-null float64
db_inserted_time                          110 non-null object
db_updated_time                           110 non-null object
rec_status                                110 non-null int64
dtypes: float64(19), int64(23), object(18)
memory usage: 51.7+ KB

In [4]:
account.head()

,id,account_status,name,owner,age,agency_client_declaration,amount_spent,attribution_spec,balance,business,...,funding_source_details,rf_spec,tos_accepted,industry_id,industry_name_large,industry_name_medium,industry_name_small,db_inserted_time,db_updated_time,rec_status
0,101474203315437,1,coca_cola_DD_Coca,550011445100868,2834.270,None,162187598,"[{'event_type': 'CLICK_THROUGH', 'window_days'...",0,"{'id': '550011445100868', 'name': 'サイバー・コミュニケー...",...,None,NaN,"{'web_custom_audience_tos': 1, 'custom_audienc...",NaN,NaN,NaN,NaN,2019-11-19 09:58:18,2019-12-18 15:00:06,3
1,103584809830089,1,Yahoo Japan Corporation_DD,550011445100868,2448.930,None,27992562,"[{'event_type': 'CLICK_THROUGH', 'window_days'...",0,"{'id': '550011445100868', 'name': 'サイバー・コミュニケー...",...,None,NaN,"{'web_custom_audience_tos': 1, 'custom_audienc...",NaN,NaN,NaN,NaN,2019-11-19 09:55:56,2019-12-18 15:00:06,3
2,105127429601931,1,"Nikkei Business Publications, Inc._DD",550011445100868,2931.190,None,126213772,"[{'event_type': 'CLICK_THROUGH', 'window_days'...",0,"{'id': '550011445100868', 'name': 'サイバー・コミュニケー...",...,None,NaN,"{'web_custom_audience_tos': 1, 'custom_audienc...",NaN,NaN,NaN,NaN,2019-11-19 09:52:15,2019-12-18 15:00:06,3
3,107523299420494,1,Nikon Imaging Japan inc._DD,550011445100868,2519.130,None,41318643,"[{'event_type': 'CLICK_THROUGH', 'window_days'...",0,"{'id': '550011445100868', 'name': 'サイバー・コミュニケー...",...,None,NaN,"{'web_custom_audience_tos': 1, 'custom_audienc...",NaN,NaN,NaN,NaN,2019-11-19 09:53:56,2019-12-18 15:00:06,3
4,142977109919742,1,"NOMURA SECURITIES CO., LTD.(Koza kaisetsu)_DD",449750032146539,145.007,None,3814295,"[{'event_type': 'CLICK_THROUGH', 'window_days'...",205105,"{'id': '449750032146539', 'name': '株式会社電通デジタル2...",...,None,NaN,"{'web_custom_audience_tos': 1, 'custom_audienc...",NaN,NaN,NaN,NaN,2019-11-19 09:50:40,2019-12-18 15:00:06,3

# Campaign

In [5]:
campaign = pd.read_csv("Data/campaign.csv")

In [6]:
campaign.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 255 entries, 0 to 254
Data columns (total 28 columns):
id                             255 non-null int64
account_id                     255 non-null int64
budget_rebalance_flag          255 non-null int64
budget_remaining               255 non-null int64
buying_type                    255 non-null object
can_create_brand_lift_study    255 non-null int64
can_use_spend_cap              255 non-null int64
configured_status              255 non-null object
created_time                   255 non-null object
effective_status               255 non-null object
name                           255 non-null object
objective                      255 non-null object
source_campaign_id             255 non-null int64
start_time                     255 non-null object
status                         255 non-null object
stop_time                      202 non-null object
updated_time                   255 non-null object
adlabels                       0 non-null float64
bid_strategy                   47 non-null object
boosted_object_id              1 non-null float64
brand_lift_studies             0 non-null float64
daily_budget                   26 non-null float64
lifetime_budget                21 non-null float64
recommendations                0 non-null float64
spend_cap                      47 non-null float64
db_inserted_time               255 non-null object
db_updated_time                255 non-null object
rec_status                     255 non-null int64
dtypes: float64(7), int64(8), object(13)
memory usage: 55.9+ KB

In [7]:
campaign.head()

,id,account_id,budget_rebalance_flag,budget_remaining,buying_type,can_create_brand_lift_study,can_use_spend_cap,configured_status,created_time,effective_status,...,bid_strategy,boosted_object_id,brand_lift_studies,daily_budget,lifetime_budget,recommendations,spend_cap,db_inserted_time,db_updated_time,rec_status
0,6019850536827,590550984380247,0,0,AUCTION,0,1,PAUSED,2014-12-19 17:58:20,PAUSED,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019-11-19 15:49:50,2019-11-19 15:49:50,2
1,6022512678027,590550984380247,0,0,AUCTION,0,1,PAUSED,2015-03-24 21:11:24,PAUSED,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019-11-19 15:49:53,2019-11-19 15:49:53,2
2,6062808431110,347882235370392,0,0,AUCTION,0,1,PAUSED,2017-03-09 11:52:46,PAUSED,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019-11-20 18:15:53,2019-11-20 18:15:53,2
3,6062859532179,710359735732704,0,0,AUCTION,0,1,PAUSED,2017-03-21 18:54:43,PAUSED,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019-11-19 19:20:48,2019-11-19 19:20:48,2
4,6080109713338,622353771199968,0,0,AUCTION,0,1,PAUSED,2017-09-22 18:38:10,PAUSED,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019-11-21 18:58:25,2019-11-21 18:58:25,2

# Adset

In [8]:
adset = pd.read_csv("Data/ad_set.csv")

In [9]:
adset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 339 entries, 0 to 338
Data columns (total 65 columns):
id                                        339 non-null int64
account_id                                339 non-null int64
campaign_id                               339 non-null int64
attribution_spec_event_type               333 non-null object
attribution_spec_windows_days             333 non-null float64
bid_amount                                28 non-null float64
bid_info                                  28 non-null object
bid_strategy                              267 non-null object
billing_event                             339 non-null object
budget_remaining                          339 non-null int64
configured_status                         339 non-null object
created_time                              339 non-null object
daily_budget                              277 non-null float64
destination_type                          339 non-null object
effective_status                          339 non-null object
end_time                                  280 non-null object
lifetime_budget                           277 non-null float64
lifetime_imps                             339 non-null int64
optimization_goal                         339 non-null object
name                                      339 non-null object
pacing_type                               277 non-null object
promoted_object_pixel_id                  219 non-null object
promoted_object_custom_event_type         0 non-null float64
recurring_budget_semantics                339 non-null int64
source_adset                              0 non-null float64
source_adset_id                           339 non-null int64
start_time                                0 non-null float64
status                                    339 non-null object
targeting_age_max                         339 non-null int64
targeting_age_min                         339 non-null int64
targeting_publisher_platforms             332 non-null object
targeting_facebook_positions              246 non-null object
targeting_audience_network_positions      83 non-null object
targeting_instagram_positions             330 non-null object
targeting_messenger_positions             80 non-null object
targeting_excluded_connections_id         0 non-null float64
targeting_excluded_connections_name       0 non-null float64
targeting_geo_locations_countries         42 non-null object
targeting_geo_locations_location_types    339 non-null object
updated_time                              339 non-null object
use_new_app_click                         339 non-null int64
time_based_ad_rotation_id_blocks          339 non-null object
time_based_ad_rotation_intervals          339 non-null object
rtb_flag                                  339 non-null object
rf_prediction_id                          339 non-null object
recommendations                           0 non-null float64
lifetime_spend_cap                        339 non-null object
lifetime_min_spend_target                 339 non-null object
instagram_actor_id                        339 non-null object
frequency_control_specs                   339 non-null object
daily_spend_cap                           339 non-null object
daily_min_spend_target                    339 non-null object
creative_sequence                         339 non-null object
adset_schedule                            339 non-null object
adlabels                                  339 non-null object
targeting_gender                          339 non-null int64
targeting_raw                             339 non-null object
reach_estimation                          322 non-null float64
removed_audience                          120 non-null float64
removed_connection                        14 non-null float64
removed_flex                              0 non-null float64
insight_status                            339 non-null int64
db_inserted_time                          339 non-null object
db_updated_time                           339 non-null object
rec_status                                339 non-null int64
dtypes: float64(14), int64(13), object(38)
memory usage: 172.3+ KB

In [10]:
adset.head()

,id,account_id,campaign_id,attribution_spec_event_type,attribution_spec_windows_days,bid_amount,bid_info,bid_strategy,billing_event,budget_remaining,...,targeting_gender,targeting_raw,reach_estimation,removed_audience,removed_connection,removed_flex,insight_status,db_inserted_time,db_updated_time,rec_status
0,6072103951310,347882235370392,6062808431110,CLICK_THROUGH,28.0,NaN,NaN,LOWEST_COST_WITHOUT_CAP,IMPRESSIONS,315503,...,2,"{""age_max"": 24, ""age_min"": 18, ""excluded_custo...",2100000.0,1.0,NaN,NaN,0,2019-11-20 21:04:17,2019-11-20 21:04:18,2
1,6072104279510,347882235370392,6062808431110,CLICK_THROUGH,28.0,14000.0,{'ACTIONS': 14000},LOWEST_COST_WITH_BID_CAP,IMPRESSIONS,351511,...,2,"{""age_max"": 65, ""age_min"": 18, ""excluded_custo...",9800000.0,1.0,NaN,NaN,0,2019-11-20 21:05:36,2019-11-20 21:05:37,2
2,6080317869938,622353771199968,6080109713338,CLICK_THROUGH,7.0,NaN,NaN,LOWEST_COST_WITHOUT_CAP,IMPRESSIONS,0,...,0,"{""age_max"": 65, ""age_min"": 18, ""custom_audienc...",310000.0,NaN,NaN,NaN,0,2019-11-21 19:18:13,2019-11-21 19:18:14,2
3,6084538621310,347882235370392,6062808431110,CLICK_THROUGH,28.0,NaN,NaN,LOWEST_COST_WITHOUT_CAP,IMPRESSIONS,65000,...,2,"{""age_max"": 40, ""age_min"": 18, ""excluded_custo...",6900000.0,1.0,NaN,NaN,0,2019-11-20 18:15:57,2019-11-20 18:15:57,2
4,6085386221830,760703960698281,6085385711230,CLICK_THROUGH,7.0,NaN,NaN,LOWEST_COST_WITHOUT_CAP,IMPRESSIONS,6000,...,1,"{""age_max"": 65, ""age_min"": 30, ""excluded_custo...",11000000.0,NaN,NaN,NaN,0,2019-11-20 16:00:19,2019-11-20 16:00:20,2

# Ad

In [11]:
ad = pd.read_csv("Data/ad.csv")

In [12]:
ad.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 397 entries, 0 to 396
Data columns (total 24 columns):
id                        397 non-null int64
account_id                397 non-null int64
adlabels                  0 non-null float64
adset_id                  397 non-null int64
bid_amount                32 non-null float64
bid_info                  32 non-null object
bid_type                  397 non-null object
campaign_id               397 non-null int64
configured_status         397 non-null object
conversion_specs          346 non-null object
created_time              397 non-null object
creative_id               397 non-null int64
effective_status          397 non-null object
last_updated_by_app_id    397 non-null int64
name                      397 non-null object
updated_time              397 non-null object
recommendations           103 non-null object
source_ad_id              397 non-null int64
status                    397 non-null object
tracking_specs            397 non-null object
insight_status            397 non-null int64
db_inserted_time          397 non-null object
db_updated_time           397 non-null object
rec_status                397 non-null int64
dtypes: float64(2), int64(9), object(13)
memory usage: 74.6+ KB

In [13]:
ad.head()

,id,account_id,adlabels,adset_id,bid_amount,bid_info,bid_type,campaign_id,configured_status,conversion_specs,...,name,updated_time,recommendations,source_ad_id,status,tracking_specs,insight_status,db_inserted_time,db_updated_time,rec_status
0,6072314762110,347882235370392,NaN,6072103951310,NaN,NaN,ABSOLUTE_OCPM,6062808431110,PAUSED,"[{'action.type': ['offsite_conversion'], 'conv...",...,33off-sorosoroapp-st_20170731,2018-01-20 20:13:35,NaN,0,PAUSED,"[{'action.type': ['offsite_conversion'], 'fb_p...",1,2019-11-20 21:04:53,2019-12-18 15:07:56,3
1,6077849462110,347882235370392,NaN,6072104279510,14000.0,{'ACTIONS': 14000},ABSOLUTE_OCPM,6062808431110,PAUSED,"[{'action.type': ['offsite_conversion'], 'conv...",...,akitoku-mottohayaku-st_20170925,2017-12-26 18:11:26,NaN,6074569406310,PAUSED,"[{'action.type': ['offsite_conversion'], 'fb_p...",1,2019-11-20 23:00:07,2019-12-18 15:07:56,3
2,6078091903510,347882235370392,NaN,6072104279510,14000.0,{'ACTIONS': 14000},ABSOLUTE_OCPM,6062808431110,PAUSED,"[{'action.type': ['offsite_conversion'], 'conv...",...,akitoku-sugoi-st_20170929,2017-12-26 18:11:26,NaN,6078091827310,PAUSED,"[{'action.type': ['offsite_conversion'], 'fb_p...",1,2019-11-20 23:00:04,2019-12-18 15:07:56,3
3,6080317872938,622353771199968,NaN,6080317869938,NaN,NaN,ABSOLUTE_OCPM,6080109713338,ACTIVE,"[{'action.type': ['offsite_conversion'], 'conv...",...,17_1001_1031_Story3_3,2017-10-06 15:23:40,NaN,6080316123538,ACTIVE,"[{'action.type': ['offsite_conversion'], 'fb_p...",1,2019-11-21 19:18:15,2019-12-18 15:13:42,3
4,6081744147910,347882235370392,NaN,6072103951310,NaN,NaN,ABSOLUTE_OCPM,6062808431110,PAUSED,"[{'action.type': ['offsite_conversion'], 'conv...",...,mg-yamaokaaoi-happy-skincare-st_20171201,2018-01-20 20:13:35,NaN,6080362722910,PAUSED,"[{'action.type': ['offsite_conversion'], 'fb_p...",1,2019-11-20 21:04:25,2019-12-18 15:07:56,3

# Creative

In [14]:
creative = pd.read_csv('Data/creative.csv')

In [15]:
creative.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 399 entries, 0 to 398
Data columns (total 41 columns):
id                                 399 non-null int64
account_id                         399 non-null int64
ad_id                              399 non-null int64
actor_id                           399 non-null int64
adlabels                           0 non-null float64
applink_treatment                  0 non-null float64
asset_feed_spec                    61 non-null object
body                               267 non-null object
branded_content_sponsor_page_id    0 non-null float64
call_to_action_type                306 non-null object
effective_instagram_story_id       336 non-null float64
effective_object_story_id          399 non-null object
image_crops                        0 non-null float64
image_hash                         200 non-null object
image_url                          200 non-null object
instagram_actor_id                 397 non-null float64
instagram_permalink_url            272 non-null object
instagram_story_id                 0 non-null float64
link_og_id                         0 non-null float64
link_url                           0 non-null float64
messenger_sponsored_message        0 non-null float64
name                               399 non-null object
object_id                          0 non-null float64
object_story_id                    1 non-null object
object_story_spec                  397 non-null object
object_type                        399 non-null object
object_url                         0 non-null float64
platform_customizations            3 non-null object
product_set_id                     0 non-null float64
recommender_settings               0 non-null float64
status                             399 non-null object
template_url                       0 non-null float64
template_url_spec                  0 non-null float64
thumbnail_url                      398 non-null object
title                              257 non-null object
url_tags                           0 non-null float64
use_page_actor_override            399 non-null int64
video_id                           121 non-null float64
db_inserted_time                   399 non-null object
db_updated_time                    399 non-null object
rec_status                         399 non-null int64
dtypes: float64(18), int64(6), object(17)
memory usage: 127.9+ KB

In [16]:
creative.head()

,id,account_id,ad_id,actor_id,adlabels,applink_treatment,asset_feed_spec,body,branded_content_sponsor_page_id,call_to_action_type,...,template_url,template_url_spec,thumbnail_url,title,url_tags,use_page_actor_override,video_id,db_inserted_time,db_updated_time,rec_status
0,6072690421110,347882235370392,6072314762110,235670193242006,NaN,NaN,NaN,全身22ヵ所を脱毛し放題！月額6800円（税抜）で手軽に始められる！,NaN,LEARN_MORE,...,NaN,NaN,https://external.xx.fbcdn.net/safe_image.php?d...,銀座カラー｜全身2,NaN,0,NaN,2019-11-20 21:04:53,2019-11-20 21:04:53,2
1,6077849495710,347882235370392,6077849462110,235670193242006,NaN,NaN,NaN,NaN,NaN,LEARN_MORE,...,NaN,NaN,https://external.xx.fbcdn.net/safe_image.php?d...,銀座カラー｜全身脱毛 スペシャルキャンペーン,NaN,0,NaN,2019-11-20 23:00:07,2019-11-20 23:00:07,2
2,6078091918510,347882235370392,6078091903510,235670193242006,NaN,NaN,NaN,NaN,NaN,LEARN_MORE,...,NaN,NaN,https://external.xx.fbcdn.net/safe_image.php?d...,銀座カラー｜全身脱毛 スペシャルキャンペーン,NaN,0,NaN,2019-11-20 23:00:05,2019-11-20 23:00:05,2
3,6080365076338,622353771199968,6080317872938,124946600918797,NaN,NaN,NaN,話題の新スマホ 好評発売中！\n話題の新スマホが、下取りと家族まとめて割で機種代金が実質¥0...,NaN,LEARN_MORE,...,NaN,NaN,https://external.xx.fbcdn.net/safe_image.php?d...,話題の新スマホ | NTTドコモ,NaN,0,NaN,2019-11-21 19:18:16,2019-11-21 19:18:16,2
4,6081744226910,347882235370392,6081744147910,235670193242006,NaN,NaN,NaN,全身22ヵ所を脱毛し放題！月額6800円（税抜）で手軽に始められる！,NaN,LEARN_MORE,...,NaN,NaN,https://external.xx.fbcdn.net/safe_image.php?d...,銀座カラー｜全身2,NaN,0,1.741314e+15,2019-11-20 21:04:26,2019-11-20 21:04:26,2

# Video

In [52]:
video = pd.read_csv('Data/insight.csv')

In [53]:
video.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 407 entries, 0 to 406
Data columns (total 63 columns):
ad_id                                407 non-null int64
account_currency                     407 non-null object
account_id                           407 non-null int64
account_name                         407 non-null object
ad_name                              407 non-null object
adset_id                             407 non-null int64
adset_name                           407 non-null object
buying_type                          407 non-null object
campaign_id                          407 non-null int64
campaign_name                        407 non-null object
canvas_avg_view_percent              0 non-null float64
canvas_avg_view_time                 0 non-null float64
clicks                               407 non-null int64
cost_per_estimated_ad_recallers      52 non-null float64
cost_per_inline_link_click           353 non-null float64
cost_per_inline_post_engagement      354 non-null float64
cost_per_unique_inline_link_click    353 non-null float64
cost_per_unique_click                354 non-null float64
cpc                                  354 non-null float64
cpm                                  407 non-null float64
cpp                                  407 non-null float64
ctr                                  407 non-null float64
date_start                           407 non-null object
date_stop                            407 non-null object
estimated_ad_recall_rate             52 non-null float64
estimated_ad_recallers               52 non-null float64
frequency                            407 non-null float64
impressions                          407 non-null int64
inline_link_click_ctr                353 non-null float64
inline_link_clicks                   394 non-null float64
inline_post_engagement               401 non-null float64
objective                            407 non-null object
place_page_name                      0 non-null float64
relevance_score                      0 non-null float64
reach                                407 non-null int64
social_spend                         0 non-null float64
spend                                407 non-null float64
unique_clicks                        398 non-null float64
unique_ctr                           407 non-null float64
unique_inline_link_click_ctr         353 non-null float64
unique_inline_link_clicks            394 non-null float64
unique_link_clicks_ctr               394 non-null float64
video_play_actions                   182 non-null float64
video_p95_watched_actions            188 non-null float64
video_p75_watched_actions            193 non-null float64
video_p50_watched_actions            201 non-null float64
video_p100_watched_actions           188 non-null float64
video_avg_percent_watched_actions    0 non-null float64
video_10_sec_watched_actions         200 non-null float64
unique_actions                       372 non-null object
cost_per_unique_action_type          372 non-null object
cost_per_action_type                 372 non-null object
cost_per_10_sec_video_view           200 non-null float64
actions                              372 non-null object
video_30_sec_watched_actions         188 non-null float64
video_avg_time_watched_actions       203 non-null float64
video_p25_watched_actions            202 non-null float64
video_3s_view                        0 non-null float64
db_inserted_time                     407 non-null object
db_updated_time                      407 non-null object
publisher_platform                   407 non-null object
platform_position                    407 non-null object
device_platform                      407 non-null object
dtypes: float64(38), int64(7), object(18)
memory usage: 200.4+ KB

In [41]:
video.head()

,id,account_id,creative_id,placement,created_time,description,embed_html,icon,picture,status,updated_time,length,source,db_inserted_time,db_updated_time,rec_status
0,131200354429138,760703960698281,6100597354030,object_story_spec,2018-06-07 06:50:47,NaN,"<iframe src=""https://www.facebook.com/plugins/...",https://static.xx.fbcdn.net/rsrc.php/v3/yD/r/D...,https://scontent.xx.fbcdn.net/v/t15.5256-10/p1...,ready,2018-09-06 04:24:01,4.138,https://video.xx.fbcdn.net/v/t39.24130-2/77983...,2019-11-20 19:42:54,2019-11-20 19:42:54,2
1,131698267659563,921453527956656,23842742462880283,object_story_spec,2018-03-05 13:04:29,NaN,"<iframe src=""https://www.facebook.com/plugins/...",https://static.xx.fbcdn.net/rsrc.php/v3/yD/r/D...,https://scontent.xx.fbcdn.net/v/t15.5256-10/p1...,ready,2018-06-12 04:55:33,9.534,https://video.xx.fbcdn.net/v/t39.24130-2/74358...,2019-11-19 23:09:48,2019-11-19 23:09:48,2
2,143442503152634,728188133949864,6109339096326,object_story_spec,2018-03-22 04:21:22,NaN,"<iframe src=""https://www.facebook.com/plugins/...",https://static.xx.fbcdn.net/rsrc.php/v3/yD/r/D...,https://scontent.xx.fbcdn.net/v/t15.5256-10/p1...,ready,2018-06-22 05:51:34,15.016,https://video.xx.fbcdn.net/v/t39.24130-2/78016...,2019-11-20 15:34:45,2019-11-20 15:34:45,2
3,148709052678268,866402673461742,23842984094160367,object_story_spec,2018-07-19 03:58:42,NaN,"<iframe src=""https://www.facebook.com/plugins/...",https://static.xx.fbcdn.net/rsrc.php/v3/yD/r/D...,https://scontent.xx.fbcdn.net/v/t15.5256-10/p1...,ready,2018-10-19 08:11:39,8.000,https://video.xx.fbcdn.net/v/t39.24130-2/71277...,2019-11-21 08:43:35,2019-11-21 08:43:35,2
4,148727972676376,866402673461742,23842984095170367,object_story_spec,2018-07-19 04:43:52,NaN,"<iframe src=""https://www.facebook.com/plugins/...",https://static.xx.fbcdn.net/rsrc.php/v3/yD/r/D...,https://scontent.xx.fbcdn.net/v/t15.5256-10/p1...,ready,2018-10-21 00:54:56,8.000,https://video.xx.fbcdn.net/v/t39.24130-2/70234...,2019-11-21 08:43:38,2019-11-21 08:43:38,2

In [42]:
video = pd.read_csv('Data/video_s3.csv')

In [43]:
video.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 5 columns):
video_id           200 non-null int64
name               200 non-null object
url                200 non-null object
aspect_ratio       0 non-null float64
downloaded_time    200 non-null object
dtypes: float64(1), int64(1), object(3)
memory usage: 7.9+ KB

In [44]:
video.head()

,video_id,name,url,aspect_ratio,downloaded_time
0,131200354429138,131200354429138_video.mp4,fb/creatives/video/131200354429138_video.mp4,NaN,2019-11-20 19:42:55
1,131698267659563,131698267659563_video.mp4,fb/creatives/video/131698267659563_video.mp4,NaN,2019-11-19 23:09:48
2,143442503152634,143442503152634_video.mp4,fb/creatives/video/143442503152634_video.mp4,NaN,2019-11-20 15:34:46
3,148709052678268,148709052678268_video.mp4,fb/creative/video/148709052678268_video.mp4,NaN,2019-11-21 08:43:36
4,148727972676376,148727972676376_video.mp4,fb/creative/video/148727972676376_video.mp4,NaN,2019-11-21 08:43:38

In [50]:
video = pd.read_csv('Data/image_s3.csv')

In [51]:
video.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 4 columns):
creative_id        200 non-null int64
name               200 non-null object
url                200 non-null object
downloaded_time    200 non-null object
dtypes: int64(1), object(3)
memory usage: 6.4+ KB